/* global $ */
$(document).ready(function () {
  console.log('hello world')
})
//empty variable for attmpted phrases
var myWord = ''
//content of phrase generated by newVoc function
var myWordLetters = []
//player attempts
var guesses = []
let howMany = 0
let youHave = 0

uniqueInputArray = myWordLetters.filter(function(elem, index, self){
    return index == self.indexOf(elem) && elem !== " "
})
function check() {
  for(var i = 0; i<guesses.length; i++ )
{
  if(!myWord.includes(guesses[i])){
    return false
  }
}
  return true
}

function confirm (){
  uniqueLetters = myWordLetters.filter(function(elem, index, self){
      return index == self.indexOf(elem) && elem !== " "
  })
//   console.log(myWord.includes(guesses))
 if(check() && (guesses.join('').length === uniqueLetters.length)) {
   alert('Congratulations! You got it all correct!')
 }
}
//random phrase selector
function newVoc () {
  myWord = list[(Math.floor(Math.random() * 49))]
  //global var "guesses" will prevent newVoc from displaying
  guesses = []
  myWordLetters = myWord.split('')
  phraseSize()
  goCount()
 }
//fn to keep record of player attempts
 function keepZGueses () {
   let letter = $(this).attr('id')
   guesses.push(letter)
   if (myWordLetters.includes(letter)) {
    //  console.log("correct")
     $(this).css('background', 'green')
     confirm()
    update()
   } else {
    //  console.log ('wrong')
     $(this).css('background', 'red')
   }
   youHave = youHave - 1
   $('#bullets').text(youHave)
   if (youHave < 0) {
     alert('Out of guesses - try another?')
     window.location.reload()
   }
 }

$('.a4all button').on('click', keepZGueses)
//fn to keep tab of attempts and pop letter on h1 when write
function update () {
  let displayables = myWordLetters.map(function (letter) {
    if(guesses.includes(letter)) {
      return letter
    }
    else {
      return '_'
    }
  }).join('')
  $('#alphabets').text(displayables)
}
//the game starter button and fn to start all over again
//without losing track of scores
$(".starter").on('click', startagain)
function startagain () {
  newVoc()
  $('.a4all button').css('background', '')
  update()
  // console.log('go!')
}
//display functions - number of letters for new phrase
function phraseSize () {
  howMany = myWordLetters.length
  $('#numBullets').text(howMany)
}
//calculator - using the phraseSize function(*2) and alerting number of attempts left
function goCount () {
  youHave = Math.round((myWordLetters.length) * 1.5)
  $('#bullets').text(youHave)
  // console.log(youHave);
  // console.log('calculating!')
}
 
